name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["type:feature", "status:needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical - Blocking other work
        - High - Important for upcoming milestone
        - Medium - Would be nice to have
        - Low - Future consideration
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Clear description of the feature
      placeholder: What would you like to see?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: Currently, I can't...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you've thought about

  - type: dropdown
    id: integration
    attributes:
      label: Related Integration
      description: Which integration is this for?
      multiple: true
      options:
        - Cloudflare
        - Salesforce
        - GitHub
        - Vercel
        - Digital Ocean
        - Claude
        - Termius
        - Mobile (iSH/Shellfish/Working Copy/Pyto)
        - State Sync
        - Hashing
        - Kanban
        - New Integration

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: This feature aligns with project goals
          required: true
